require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'rake/testtask'
require 'spec/rake/spectask'

require 'lib/anvil/version'

NAME = "anvil"
AUTHOR = "Lance Carlson"
EMAIL = "lancecarlson@gmail.com"
HOMEPAGE = "http://anvil.rubyforge.org"
SUMMARY = "Database integration for Anvil"
DESCRIPTION = "A collection of DSL's and frameworks that take full advantage of Ruby's powerful syntax"

windows = (PLATFORM =~ /win32|cygwin/)

SUDO = windows ? "" : "sudo"

dist_dirs = [ "lib", "spec" ]

spec = Gem::Specification.new do |s|
  s.name = NAME
  s.version = Anvil::VERSION
  s.platform = Gem::Platform::RUBY
  s.summary = SUMMARY
  s.description = DESCRIPTION
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  s.has_rdoc = true
  s.executables = ['anvil']

  s.add_dependency('anvil-db')
  s.add_dependency('anvil-gen')
  s.add_dependency('anvil-gui')
  s.add_dependency('kissgen')
  s.add_dependency('rspec')
  s.add_dependency('rake')

  s.files = [ "MIT-LICENSE", "Rakefile", "README" ]
  dist_dirs.each do |dir|
    s.files = s.files + Dir.glob("#{dir}/**/*")
  end
  
  s.rubyforge_project = 'anvil'
end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
end

Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = 'doc'
  rdoc.title    = 'Anvil'
  rdoc.options << '--line-numbers' << '--inline-source' << '-A cattr_accessor=object'
  rdoc.options << '--charset' << 'utf-8'
  rdoc.rdoc_files.include('README', 'MIT-LICENSE')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

desc 'Run :package and install the resulting .gem'
task :install => :package do
  sh %{#{SUDO} gem install pkg/#{NAME}-#{Anvil::VERSION} --no-rdoc --no-ri}
end

desc 'Run :clean and uninstall the .gem'
task :uninstall => [:clean] do
  sh %{#{SUDO} gem uninstall #{NAME}}
end

desc "Run all specs"
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.spec_opts = ['--options', 'spec.opts']
end

desc "Run all specs and generate an rcov report"
Spec::Rake::SpecTask.new('spec:rcov') do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.spec_opts = ['--options', 'spec.opts']
  t.rcov = true
  t.rcov_dir = 'coverage'
  t.rcov_opts = ['--exclude', 'gems', '--exclude', 'spec']
end

task :release => :package do
  sh %{rubyforge add_release #{NAME} #{NAME} "#{VERSION}" pkg/#{NAME}-#{Anvil::VERSION}.gem}
end